Sac-State-Mobile-App-The-Nest/SAC-LIFE

SacStateApp/.dockerignore
SacStateApp/Dockerfile
admin-web/.dockerignore
admin-web/Dockerfile
backend-api/.dockerignore
backend-api/Dockerfile
docker-compose.yml

The Dockerfile is the instruction on how the container is created.
docker-compose groups all the containers together.

#25 Created Dockerfile and docker-compose to create containers

---

SacStateApp/server.js

Added more sample queries to server.js

Jira Task #30

---

backend-api/package-lock.json
backend-api/package.json
backend-api/routes/campus_services.js
backend-api/routes/students.js
backend-api/routes/tags.js
backend-api/server.js

#45, #51 Created api that fetches data from Azure SQL database.

---

SacStateApp/src/screens/DashboardScreen.js
backend-api/config.js
backend-api/package-lock.json
backend-api/package.json
backend-api/routes/campus_services.js
backend-api/routes/students.js
backend-api/routes/tags.js
backend-api/server.js

1. Retrieved user info based on an actual user login and to show user's first, middle, and last name on dashboard. 
2. Created another function to retrieve user's services recommended based on their std_id. Information is displayed in dashboard.js but no UI yet.
4. Moved server config to separate file so data can be used in other api routes
5. Modified/added some api code

Jira39-Task 46

---

SacStateApp/package-lock.json
SacStateApp/src/screens/DashboardScreen.js
SacStateApp/src/screens/MessengerScreen.js
SacStateApp/src/screens/SettingsScreen.js

Implemented a navigator bar and removed some uneccessary text from the Dashboard page. Added two new screens, SettingsScreen and MessengerScreen as empty screens for future navigation bar implementation.

JIRA#70 (Navigation Bar)

---

backend-api/package-lock.json
backend-api/package.json
backend-api/routes/login_info.js

Merging new JWT code to Christian's codebase

Redirect to dashboard/profile creation

---

SacStateApp/package-lock.json
SacStateApp/package.json
SacStateApp/src/screens/LogInScreen.js
backend-api/routes/login_info.js

Connected backend route to the frontend to pull JWT and first_login boolean.
The app now redirects to the profile creation screen or dashboard based on the boolean.
- Removed protected route in login_info, replaced with /check-login-bool

JIRA #58 - User should be redirected to dashboard or profile creation

---

SacStateApp/src/screens/LogInScreen.js
SacStateApp/src/screens/ProfileCreationScreen.js
backend-api/routes/students.js

- change sql boolean after profile creation
- redirect to correct screen based on sql boolean
- use AsyncStorage to get token

#63 change sql boolean after profile creation

---

SacStateApp/babel.config.js
SacStateApp/package-lock.json
SacStateApp/package.json
SacStateApp/src/screens/DashboardScreen.js
SacStateApp/src/screens/LogInScreen.js
backend-api/routes/campus_services.js
backend-api/routes/students.js
backend-api/server.js

- Added env variable so making api requests will only require you to change env IP variable
- Frontend shows user and services recommended with clickable buttons that link to service site
- Front/backend code implements JWT that Vinny created

JIRA 71 - Generate Unique Dashboard

---

SacStateApp/src/screens/LogInScreen.js
SacStateApp/src/screens/ProfileCreationScreen.js
backend-api/routes/campus_services.js

- added env file configuration to ProfileCreationScreen
- fixed duplicate campus services showing

- fixed duplicate campus services showing minor bug

---

SacStateApp/src/screens/DashboardScreen.js
SacStateApp/src/screens/ProfileScreen.js

just moved the name to display on the profile screen and fixed a gap above the calendar

moved name to profile screen

---

SacStateApp/package-lock.json
SacStateApp/src/screens/WelcomeScreen.js

Fixed WelcomeScreen navigation to LogIn

UN1456: Fixed Navigation to Login

---

backend-api/package-lock.json
backend-api/package.json
backend-api/routes/events.js
backend-api/server.js

used node-fetch and xml2js.
RSS Feed to SQL. Able to get title, description, event type, link, and date.
SQL format (DATETIME - format: YYYY-MM-DD HH:MI:SS)

UNI1456-90: Get Events Data

---

SacStateApp/src/SettingsStyles/SettingsStyles.js
SacStateApp/src/screens/SettingsScreen.js

Updated the SettingsScreen to look better.

UN1456: Changed Setting UI

---

SacStateApp/src/DashboardAPI/api.js
backend-api/routes/students.js

I created 4 api's in the backend-api/routes/students.js file: get student area of study, get student year of study, update student year of study, and update student area of study. I also added 4 functions inside the SacStateApp/src/DashboardAPI/api.js file which make it easy for frontend developers to call the api's i made.

UNI456-93: For User profile data and updates. Created 4 api's in backend and 4 functions in frontend

---

SacStateApp/src/screens/SettingsScreen.js

I updated the profile screen to display the student name, college, and grade after Randy made his changes to the profile page

Profile screen shows the user's name, college, and grade now

---

SacStateApp/package-lock.json
SacStateApp/package.json
SacStateApp/src/DashboardComponents/ChatWidget.js
chatbot-api/dfserver.js
package-lock.json
package.json

also added links to ai chatbot and better logic to give more acurate and helpful responses but all messages to chatbot nad responses along with time is stored in database

UNI456-99-AI-chatbot stores messages

---

SacStateApp/src/DashboardComponents/CalendarComponent.js
SacStateApp/src/DashboardStyles/CalendarStyles.js
backend-api/routes/events.js

User is able to see all Sac State events for a date when they click on it. It will only show events that have not already passed.
- Created an api in /events.js to read from events from database
- Called the api in the frontend and made some UI changes
This is what it looks like when there are events and also when there are none for a date

UNI456-111: User is able to see all sac state student events for a date

---

SacStateApp/package-lock.json
SacStateApp/package.json
SacStateApp/src/DashboardAPI/api.js
SacStateApp/src/DashboardComponents/CalendarComponent.js
backend-api/routes/events.js

- Created a database for student created event
- Created Post for created event (backend: events.js)
- Changed CalendarCompoenent frontend to add time when creating event
- Created api on frontend to use (frontend: api.js)
- Imported DateTimePicker

UNI1456-112: Send created event to server

---

SacStateApp/src/DashboardComponents/CalendarComponent.js

fixed a bug in CalendarComponent.js. It imported some of the same stuff twice

fixed bug - CalendarComponent.js too much imports

---

SacStateApp/package-lock.json
SacStateApp/src/ProfileCreationStyles/ProfileCreationStyles.js
SacStateApp/src/screens/ProfileCreationScreen.js

The next button is now permanently placed on the rightside, especially with the first question. Fade in and Fade out transition animations were added to the movement of questions. Added a 10 year limit to the graduation year input.

Origin/uni456 113/pcs transitions

---

SacStateApp/package-lock.json
SacStateApp/package.json
SacStateApp/src/DashboardComponents/CalendarComponent.js
SacStateApp/src/DashboardStyles/CalendarStyles.js
backend-api/routes/events.js

1. Created an api so users can get their events that they created
2. Displays user created events for that specific user
3. The event, when clicked, now expands and shows the user a description as well as a link if there exists one
4. Fixed bug where event won't show if date is not clicked

UNI456-138: User can see their own events and click to expand all events

---

SacStateApp/package-lock.json
SacStateApp/package.json
SacStateApp/src/DashboardComponents/DashboardTab.js
SacStateApp/src/SacStateColors/GeneralColors.js
SacStateApp/src/SettingsScreenComponents/ProfileModals.js
SacStateApp/src/SettingsStyles/SettingsStyles.js
SacStateApp/src/screens/AllServicesScreen.js
SacStateApp/src/screens/LogInScreen.js
SacStateApp/src/screens/SettingsScreen.js
backend-api/routes/login_info.js
backend-api/routes/students.js

(1) A user can edit their preferred name, it'll check to make sure the name isn't their current one.
(2) A user can logout, clicking back arrow won't sign them in since stack is cleared and jwt is cleared.
(3) A user can change their password, has checks in place to make sure it isn't the current one and at least 10 characters in length.
(4) A user can download their chatbot history as a pdf file.
(5) A user can deactivate their account, it'll open up 2 prompts to confirm the deactivation. i added a is_active column in the login_info table, also modified the login code to check if that value is true or false so the account isn't actually deleted.
(6) A user can also view some info about the app, needs polishing still.
(7) Fixed a minor bug in the "Your Services" page so users can search …

Profile customization/uni456 129 make profile settings screen functional

---

backend-api/package-lock.json
backend-api/package.json
backend-api/testing_scrape.js

- able to get title, url, description
- still needs work on getting the correct DATETIME

UNI456-132: Webscrape sac state events

---

SacStateApp/src/screens/WellnessHomeScreen.js
SacStateApp/src/screens/WellnessScreen.js
backend-api/routes/students.js

Able to get and post wellness answers
- 2 Columns added to students table for wellness score and answers
- Uses API GET and POST instead of asyncstorage

UNI456-157: Able to get and post wellness answers

---

backend-api/sac_events_backup.json
backend-api/scrape.js
backend-api/upload.js

- scrape.js: grabs events for 3 months and store in a json file
- upload.js: truncate sac events table and bulk insert sac events that was stored in json file

UNI456-132: refactor webscraping using playwright

---

admin-web/package-lock.json
admin-web/package.json
admin-web/src/components/Analytics.js
admin-web/src/css/Analytics.css
admin-web/src/css/App.css
backend-api/routes/admin_routes/adminRoutes.js
backend-api/routes/login_info.js

- Admins can view the total active accounts and inactive ones
- Admins can see the total logins for today, past week, and past month
- Admins can interact with a graph to view a timeline of logins

UNI456-149: Admin Analytics Completed

---

SacStateApp/App.js
SacStateApp/src/screens/HomeScreen.js
SacStateApp/src/screens/LogInScreen.js
SacStateApp/src/screens/SignUpScreen.js
SacStateApp/src/screens/VerificationScreen.js
SacStateApp/src/styles/VerificationScreenStyles.js
backend-api/package-lock.json
backend-api/package.json
backend-api/routes/login_info.js
backend-api/routes/signup.js
backend-api/routes/students.js
backend-api/server.js
email-verify-web/index.html
email-verify-web/script.js
email-verify-web/styles.css

IMPORTANT:
email-verify-web
- script.js: check if link is correct (should be backend server)
backend-api
- routes/signup.js: CLIENT_URL needs to be changed to email-verify-web link
Description:
- Able to verify @csus email using SendGrid
- Created an email account to use with SendGrid
- Created verification page
- Created VerificationScreen so users can resend email verification

UNI456-164: Finalize login process

---

SacStateApp/src/DashboardComponents/CalendarComponent.js
SacStateApp/src/SettingsScreenComponents/ProfileModals.js
SacStateApp/src/screens/SettingsScreen.js
admin-web/package-lock.json
admin-web/package.json
admin-web/src/components/Students.js
admin-web/src/tests/analytics.test.js
admin-web/src/tests/chatbotlogs.test.js
admin-web/src/tests/login.test.js
admin-web/src/tests/students.test.js

- Created a folder for tests
- Created tests for admin analytics, chatbotlogs, login, and students pages. All tests passed and documented in drive.
- Some components were missing BASE_URL so imported them
- Settings screen updating name and password fixed, profanity filter used incorrectly
- Tested all of app's features and they all should work correctly now

UNI456-168: Admin web testing components with jest
